version: '3.7'

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    expose:
      - '5432'
    networks:
      - interconnect
  redis:
    image: redis:latest
    expose:
      - '6379'
    networks:
      - interconnect
  app:
    build: .
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    entrypoint: ["/start.sh"]
    ports:
      - '8000:8000'
    networks:
      - interconnect
  faststream:
    build: .
    command: taskiq scheduler app:scheduler
    volumes:
      - ./src:/app
    depends_on:
      - app
      - redis

volumes:
  pgdata:

networks:
  interconnect:
    driver: bridge
